# Generated by Django 4.2.24 on 2025-09-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_remove_courseallocation_session"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsandevents",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="summary_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="summary_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="summary_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="summary_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newsandevents",
            name="summary_vi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Semester",
        ),
        migrations.DeleteModel(
            name="Session",
        ),
    ]
