# Generated by Django 4.2.24 on 2025-09-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_newsandevents_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsandevents",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="news_attachments/%Y/%m/%d/",
                verbose_name="Attachment",
            ),
        ),
    ]
