# Generated by Django 4.2.24 on 2025-10-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_newsandevents_attachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsandevents",
            name="summary_es",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="summary_fr",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="summary_ru",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="title_fr",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="title_ru",
        ),
    ]
