# Generated by Django 4.2.24 on 2025-09-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseallocation",
            name="session",
        ),
    ]
