# Generated by Django 4.2.24 on 2025-10-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_remove_courseallocation_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="summary_es",
        ),
        migrations.RemoveField(
            model_name="course",
            name="summary_fr",
        ),
        migrations.RemoveField(
            model_name="course",
            name="summary_ru",
        ),
        migrations.RemoveField(
            model_name="course",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="course",
            name="title_fr",
        ),
        migrations.RemoveField(
            model_name="course",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="program",
            name="summary_es",
        ),
        migrations.RemoveField(
            model_name="program",
            name="summary_fr",
        ),
        migrations.RemoveField(
            model_name="program",
            name="summary_ru",
        ),
        migrations.RemoveField(
            model_name="program",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="program",
            name="title_fr",
        ),
        migrations.RemoveField(
            model_name="program",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="title_fr",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="summary_es",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="summary_fr",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="summary_ru",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="title_fr",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="title_ru",
        ),
    ]
