# Generated by Django 4.0.8 on 2025-09-07 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_summary_vi_course_title_vi_program_summary_vi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('SQ', 'Sĩ quan'), ('QNCN', 'Quân nhân chuyên nghiệp'), ('CS', 'Chiến sĩ')], max_length=25),
        ),
    ]
