# Generated by Django 4.0.8 on 2025-09-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_update_degree_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_elective',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
