# Generated by Django 4.2.24 on 2025-10-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="choice_text_es",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice_text_fr",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice_text_ru",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content_es",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content_fr",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation_es",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation_fr",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation_ru",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description_es",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description_fr",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title_fr",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title_ru",
        ),
    ]
