# Generated by Django 4.0.8 on 2025-09-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_essayquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text_vi',
            field=models.CharField(help_text='Enter the choice text that you want displayed', max_length=1000, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='question',
            name='content_vi',
            field=models.CharField(help_text='Enter the question text that you want displayed', max_length=1000, null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_vi',
            field=models.TextField(blank=True, help_text='Explanation to be shown after the question has been answered.', max_length=2000, null=True, verbose_name='Explanation'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_vi',
            field=models.TextField(blank=True, help_text='A detailed description of the quiz', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_vi',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(blank=True, choices=[('assignment', 'Assignment'), ('exam', 'Exam'), ('practice', 'Practice Quiz')], max_length=20, verbose_name='Category'),
        ),
    ]
