# Generated by Django 4.2.24 on 2025-09-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="ID No."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/%y/%m/%d/"
            ),
        ),
    ]
