# Generated by Django 4.0.8 on 2025-09-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('QNCN', 'Quân nhân chuyên nghiệp'), ('CS', 'Chiến sĩ')], max_length=25, null=True),
        ),
    ]
