# Generated by Django 4.2.24 on 2025-09-21 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_student_id_number_alter_user_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="classes",
            field=models.CharField(
                choices=[
                    ("TSGNSN", "TS-GN Sóng ngắn"),
                    ("TSGNSCN", "TS-GN Sóng cực ngắn"),
                    ("TSGNĐK&NTNB", "TS-GN ĐK&NTNB"),
                    ("TSC", "Trạm Sửa chữa"),
                    ("BCHd", "Ban chỉ huy Tiểu đoàn"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("SQ", "Sĩ quan"),
                            ("QNCN", "Quân nhân chuyên nghiệp"),
                            ("CS", "Chiến sĩ"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "classes",
                    models.CharField(
                        choices=[
                            ("TSGNSN", "TS-GN Sóng ngắn"),
                            ("TSGNSCN", "TS-GN Sóng cực ngắn"),
                            ("TSGNĐK&NTNB", "TS-GN ĐK&NTNB"),
                            ("TSC", "Trạm Sửa chữa"),
                            ("BCHd", "Ban chỉ huy Tiểu đoàn"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID No.",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-staff__date_joined",),
            },
        ),
    ]
