# Generated by Django 4.0.8 on 2025-09-05 13:27

from django.db import migrations

def update_student_levels(apps, schema_editor):
    """
    Lấy các bản ghi Student cũ và cập nhật trường 'level'.
    """
    Student = apps.get_model('accounts', 'Student')
    db_alias = schema_editor.connection.alias

    # Đổi tất cả 'Bachelor' thành 'qncn'
    Student.objects.using(db_alias).filter(level='Bachelor').update(level='qncn')

    # Đổi tất cả 'Master' thành 'cs'
    Student.objects.using(db_alias).filter(level='Master').update(level='cs')

def revert_student_levels(apps, schema_editor):
    """
    Hàm hoàn tác: đổi ngược lại nếu cần.
    """
    Student = apps.get_model('accounts', 'Student')
    db_alias = schema_editor.connection.alias

    Student.objects.using(db_alias).filter(level='qncn').update(level='Bachelor')
    Student.objects.using(db_alias).filter(level='cs').update(level='Master')


class Migration(migrations.Migration):

    dependencies = [
        # Dòng này Django đã tự tạo, hãy giữ nguyên tên file migration trước đó
        ('accounts', '0004_alter_student_level'), 
    ]

    operations = [
        migrations.RunPython(update_student_levels, revert_student_levels),
    ]