# Generated by Django 4.2.24 on 2025-09-21 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_student_classes_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="level",
        ),
    ]
