# Generated by Django 4.0.8 on 2025-09-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_update_student_level_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.CharField(blank=True, choices=[('TS-GN Sóng ngắn', 'TS-GN Sóng ngắn'), ('TS-GN Sóng cực ngắn', 'TS-GN Sóng cực ngắn'), ('TS-GN ĐK&NTNB', 'TS-GN ĐK&NTNB'), ('Trạm Sửa chữa', 'Trạm Sửa chữa')], max_length=20, null=True, verbose_name='Trạm'),
        ),
    ]
