# Generated by Django 4.2.24 on 2025-10-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_staff_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="classes",
            field=models.CharField(
                choices=[
                    ("TSGNSN", "TS-GN Sóng ngắn"),
                    ("TSGNSCN", "TS-GN Sóng cực ngắn"),
                    ("TSGNĐK&NTNB", "TS-GN ĐK&NTNB"),
                    ("TSC", "Trạm Sửa chữa"),
                    ("BCHd", "Ban chỉ huy Tiểu đoàn"),
                    ("NQ", "Nuôi quân"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="classes",
            field=models.CharField(
                choices=[
                    ("TSGNSN", "TS-GN Sóng ngắn"),
                    ("TSGNSCN", "TS-GN Sóng cực ngắn"),
                    ("TSGNĐK&NTNB", "TS-GN ĐK&NTNB"),
                    ("TSC", "Trạm Sửa chữa"),
                    ("BCHd", "Ban chỉ huy Tiểu đoàn"),
                    ("NQ", "Nuôi quân"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
