# Generated by Django 4.0.8 on 2025-09-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.CharField(choices=[('TSGNSN', 'TS-GN Sóng ngắn'), ('TSGNSCN', 'TS-GN Sóng cực ngắn'), ('TSGNĐK&NTNB', 'TS-GN ĐK&NTNB'), ('TSC', 'Trạm Sửa chữa')], max_length=25, null=True),
        ),
    ]
