# Generated by Django 4.0.8 on 2025-09-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('SQ', 'Sĩ quan'), ('QNCN', 'Quân nhân chuyên nghiệp'), ('CS', 'Chiến sĩ')], max_length=25, null=True),
        ),
    ]
